version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      QUEQUE_URL: https://sqs.us-east-1.amazonaws.com/489853078485/worker-input
    volumes:
      - ~/.aws/:/root/.aws

  external-api:
    build: ./external-api
    ports:
      - "8081:8080"
    depends_on:
      - api

  worker-input:
    build: ./worker-input
    depends_on:
      - api
    environment:
      INPUT_QUEQUE_URL: https://sqs.us-east-1.amazonaws.com/489853078485/worker-input
      OUTPUT_QUEQUE_URL: https://sqs.us-east-1.amazonaws.com/489853078485/worker-output
      FRACTAL_API_BASE_URL: http://external-api:8080
    volumes:
      - ~/.aws/:/root/.aws

  worker-output:
    build: ./worker-output
    depends_on:
      - api
    environment:
      OUTPUT_QUEQUE_URL: https://sqs.us-east-1.amazonaws.com/489853078485/worker-output
    volumes:
      - ~/.aws/:/root/.aws

