apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: sqs-service-account
      containers:
        - name: api
          image:  ghcr.io/csepulveda/post-autoscaling-resources-api:main
          ports:
            - containerPort: 8080
          env:
            - name: QUEQUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/489853078485/messages"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-api
  template:
    metadata:
      labels:
        app: external-api
    spec:
      containers:
        - name: external-api
          image:  ghcr.io/csepulveda/post-autoscaling-resources-external-api:main
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: sqs-service-account
      containers:
        - name: worker
          image: ghcr.io/csepulveda/post-autoscaling-resources-worker:main
          env:
            - name: QUEQUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/489853078485/messages"
            - name: FRACTAL_API_BASE_URL
              value: "http://external-api:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: external-api-service
spec:
  selector:
    app: external-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqs-service-account