---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-input-sqs-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-input-deployment
  minReplicaCount: 0
  maxReplicaCount: 4
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/489853078485/worker-input
        queueLength: "20"
        awsRegion: us-east-1
        identityOwner: operator